In [2]:
import sqlite3

# Database connection
conn = sqlite3.connect("atm.db")
cur = conn.cursor()

# Table create (run once)
cur.execute('''
CREATE TABLE IF NOT EXISTS accounts (
    acc_no INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    pin TEXT,
    balance REAL
)
''')
conn.commit()

In [ ]:
#project

In [50]:
import sqlite3

conn = sqlite3.connect('shopping.db')
cursor = conn.cursor()

cursor.execute('''
CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    price REAL NOT NULL
)
''')

cursor.execute('''
CREATE TABLE IF NOT EXISTS cart (
    product_id INTEGER,
    quantity INTEGER,
    FOREIGN KEY(product_id) REFERENCES products(id)
)
''')

conn.commit()

def add_product(name, price):
    cursor.execute("INSERT INTO products (name, price) VALUES (?, ?)", (name, price))
    conn.commit()
    print(f"Product '{name}' added successfully.")

def view_products():
    cursor.execute("SELECT * FROM products")
    rows = cursor.fetchall()
    print("Available Products:")
    for row in rows:
        print(f"ID: {row[0]}, Name: {row[1]}, Price: ₹{row[2]}")

def add_to_cart(product_id, quantity):
    cursor.execute("INSERT INTO cart (product_id, quantity) VALUES (?, ?)", (product_id, quantity))
    conn.commit()
    print(f"Product ID {product_id} added to cart (Quantity: {quantity})")

def view_cart_and_bill():
    cursor.execute('''
        SELECT p.name, p.price, c.quantity, p.price * c.quantity as total
        FROM cart c
        JOIN products p ON c.product_id = p.id
    ''')
    rows = cursor.fetchall()
    if not rows:
        print("Your cart is empty.")
        return
    
    grand_total = 0
    print("Cart Summary:")
    for name, price, qty, total in rows:
        print(f"{name} - ₹{price} x {qty} = ₹{total}")
        grand_total += total
    print("\n Total Bill: ₹", grand_total)

def clear_cart():
    cursor.execute("DELETE FROM cart")
    conn.commit()
    print("Cart cleared.")

view_products()

#add_product("8 PM", 500)
#add_product("antiquity blue", 1200)
#add_product("chicken", 300)

while True:
    product_id = input("Enter Product ID (or type 'done' to finish): ")
    if product_id.lower() == 'done':
        break
    quantity = input("Enter quantity: ")
    add_to_cart(int(product_id), int(quantity))

view_cart_and_bill()

Available Products:
ID: 52, Name: cap, Price: ₹500.0
ID: 53, Name: tshirt, Price: ₹1200.0
ID: 54, Name: chicken, Price: ₹300.0
ID: 55, Name: 8 PM, Price: ₹500.0
ID: 56, Name: antiquity blue, Price: ₹1200.0
ID: 57, Name: chicken, Price: ₹300.0


Enter Product ID (or type 'done' to finish):  56
Enter quantity:  1


Product ID 56 added to cart (Quantity: 1)


Enter Product ID (or type 'done' to finish):  55
Enter quantity:  2


Product ID 55 added to cart (Quantity: 2)


Enter Product ID (or type 'done' to finish):  57
Enter quantity:  3


Product ID 57 added to cart (Quantity: 3)


Enter Product ID (or type 'done' to finish):  done


Cart Summary:
chicken - ₹300.0 x 2 = ₹600.0
cap - ₹500.0 x 3 = ₹1500.0
antiquity blue - ₹1200.0 x 1 = ₹1200.0
8 PM - ₹500.0 x 2 = ₹1000.0
chicken - ₹300.0 x 3 = ₹900.0

 Total Bill: ₹ 5200.0


In [ ]:
#numpy

In [53]:
import numpy as np

a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [54]:
arr= np.array([[1,2,3],[4,5,6]])

print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64


In [58]:
import numpy as np
print(np.zeros((2,3)))
print(np.ones((3,3)))
print(np.eye(3,3))
print(np.full((2,2), 7))
print(np.arange(1,10,2))
print(np.linspace(1,5,4))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7]
 [7 7]]
[1 3 5 7 9]
[1.         2.33333333 3.66666667 5.        ]


In [63]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)

print(a * b)

print(a ** 2)

print (np.sqrt (a))

print(np.mean (a))

[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
2.0


In [69]:
arr = np.array ([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr))

print(np.min(arr))

print(np.max(arr))

print(np.sum(arr, axis=0))

21
1
6
[5 7 9]


In [70]:
arr = np.array([[1, 2], [3, 4]])
print(arr. flatten())

[1 2 3 4]


In [72]:
arr = np.array ([[1, 2, 3], [4, 5, 6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [75]:
a = np.array ([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 21]])
print(np.dot (a, b))

[[ 4 42]
 [10 84]]
